branches:
  only:
  - master

language: cpp

os:
  - linux
  - osx

dist: xenial

compiler:
  - gcc
  - clang

jobs:
  # do this here rather than in matrix since we don't need multiple compilers
  include:
    - os: windows

before_script:
  - cd test
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script: 
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      make 
      ./bin/geometry-central-test
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      make 
      ./bin/geometry-central-test
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      cmake --build "."
      ls
      ./bin/Debug/geometry-central-test.exe
    fi
